/* Generated By:JavaCC: Do not edit this line. ASTGentorTreeConstants.java Version 6.0_1 */
package czlab.tecs.ast;

public interface ASTGentorTreeConstants
{
  public int JJTCLASSDEC = 0;
  public int JJTKEYWORD = 1;
  public int JJTSYMBOL = 2;
  public int JJTCLASSVARDEC = 3;
  public int JJTVOID = 4;
  public int JJTSUBROUTINEDEC = 5;
  public int JJTPARAMETERLIST = 6;
  public int JJTSUBROUTINEBODY = 7;
  public int JJTVARDEC = 8;
  public int JJTSTATEMENTS = 9;
  public int JJTLETSTATEMENT = 10;
  public int JJTIFSTATEMENT = 11;
  public int JJTWHILESTATEMENT = 12;
  public int JJTDOSTATEMENT = 13;
  public int JJTRETURNSTATEMENT = 14;
  public int JJTEXPRESSION = 15;
  public int JJTTERM = 16;
  public int JJTEXPRESSIONLIST = 17;
  public int JJTSCOPEDCALL = 18;
  public int JJTINTEGERCONSTANT = 19;
  public int JJTSTRINGCONSTANT = 20;
  public int JJTIDENTIFIER = 21;


  public String[] jjtNodeName = {
    "ClassDec",
    "Keyword",
    "Symbol",
    "ClassVarDec",
    "void",
    "SubroutineDec",
    "ParameterList",
    "SubroutineBody",
    "VarDec",
    "Statements",
    "LetStatement",
    "IfStatement",
    "WhileStatement",
    "DoStatement",
    "ReturnStatement",
    "Expression",
    "Term",
    "ExpressionList",
    "ScopedCall",
    "IntegerConstant",
    "StringConstant",
    "Identifier",
  };
}
/* JavaCC - OriginalChecksum=8e21d8811fa6e2a48fbdacc17527a114 (do not edit this line) */
