/* Generated By:JJTree: Do not edit this line. ClassVarDec.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.ast;

public
class ClassVarDec extends ASTNode {
  public ClassVarDec(int id) {
    super(id);
  }

  public ClassVarDec(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e37948ff8f6b498343a4fcf9a2bff787 (do not edit this line) */
