/* Generated By:JJTree: Do not edit this line. ClassDec.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.ast;

public
class ClassDec extends SimpleNode {
  public ClassDec(int id) {
    super(id);
  }

  public ClassDec(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2e75193060e4e13f788f5237eeaf1ed4 (do not edit this line) */
