/* Generated By:JJTree: Do not edit this line. ClassDec.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.ast;

public
class ClassDec extends ASTNode {
  public ClassDec(int id) {
    super(id);
  }

  public ClassDec(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=29f5d2a1a2b833e9cbb5f191b4d6daeb (do not edit this line) */
