/* Generated By:JJTree: Do not edit this line. ClassVarDec.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.ast;

public
class ClassVarDec extends SimpleNode {
  public ClassVarDec(int id) {
    super(id);
  }

  public ClassVarDec(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7a47fd37a3037c87a0ff8dd6d9ba124c (do not edit this line) */
