/* Generated By:JJTree: Do not edit this line. DoStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.ast;

public
class DoStatement extends SimpleNode {
  public DoStatement(int id) {
    super(id);
  }

  public DoStatement(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=354e816cdf1021c99d47b7ced25e0ef0 (do not edit this line) */
