/* Generated By:JJTree: Do not edit this line. Expression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.ast;

public
class Expression extends ASTNode {
  public Expression(int id) {
    super(id);
  }

  public Expression(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=32f747e0dc481fc13c8071802937de58 (do not edit this line) */
