/* Generated By:JJTree: Do not edit this line. Expression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.ast;

public
class Expression extends SimpleNode {
  public Expression(int id) {
    super(id);
  }

  public Expression(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2620c2112dddd66c07fe506178146844 (do not edit this line) */
