/* Generated By:JJTree: Do not edit this line. ExpressionList.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.ast;

public
class ExpressionList extends ASTNode {
  public ExpressionList(int id) {
    super(id);
  }

  public ExpressionList(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=caf99ffa36a3e9594ecf15d448f2d632 (do not edit this line) */
