/* Generated By:JJTree: Do not edit this line. ExpressionList.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.ast;

public
class ExpressionList extends SimpleNode {
  public ExpressionList(int id) {
    super(id);
  }

  public ExpressionList(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=96d829d5a45f07a8d2b866cac7955568 (do not edit this line) */
