/* Generated By:JJTree: Do not edit this line. Identifier.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.ast;

public
class Identifier extends SimpleNode {
  public Identifier(int id) {
    super(id);
  }

  public Identifier(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a71a9207e3de7da4ff297cab8cf1e912 (do not edit this line) */
