/* Generated By:JJTree: Do not edit this line. IfStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.ast;

public
class IfStatement extends ASTNode {
  public IfStatement(int id) {
    super(id);
  }

  public IfStatement(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=22bee4c4bb5e0b5266a132f980cf1078 (do not edit this line) */
