/* Generated By:JJTree: Do not edit this line. IntegerConstant.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.ast;

public
class IntegerConstant extends SimpleNode {
  public IntegerConstant(int id) {
    super(id);
  }

  public IntegerConstant(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=038a45db9faabe452c64ab7f1d5078b6 (do not edit this line) */
