/* Generated By:JJTree: Do not edit this line. IntegerConstant.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.ast;

public
class IntegerConstant extends ASTNode {
  public IntegerConstant(int id) {
    super(id);
  }

  public IntegerConstant(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0654c79e9ea6e60885e41e3f64782753 (do not edit this line) */
