/* Generated By:JJTree: Do not edit this line. Keyword.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.ast;

public
class Keyword extends SimpleNode {
  public Keyword(int id) {
    super(id);
  }

  public Keyword(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=277145d3dc8a7b9dac2fb3d692754259 (do not edit this line) */
