/* Generated By:JJTree: Do not edit this line. LetStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.ast;

public
class LetStatement extends ASTNode {
  public LetStatement(int id) {
    super(id);
  }

  public LetStatement(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0ee50a152f6b010dc0964fec3ae357df (do not edit this line) */
