/* Generated By:JJTree: Do not edit this line. LetStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.ast;

public
class LetStatement extends SimpleNode {
  public LetStatement(int id) {
    super(id);
  }

  public LetStatement(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fdfb497cda4566a545cf8c7a218321fa (do not edit this line) */
