/* Generated By:JJTree: Do not edit this line. ParameterList.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.ast;

public
class ParameterList extends SimpleNode {
  public ParameterList(int id) {
    super(id);
  }

  public ParameterList(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=10d801f8a794e751e28271b1dfacabd5 (do not edit this line) */
