/* Generated By:JJTree: Do not edit this line. ParameterList.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.ast;

public
class ParameterList extends ASTNode {
  public ParameterList(int id) {
    super(id);
  }

  public ParameterList(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0ea93f498e9a20c043183d63b3cf556c (do not edit this line) */
