/* Generated By:JJTree: Do not edit this line. ReturnStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.ast;

public
class ReturnStatement extends SimpleNode {
  public ReturnStatement(int id) {
    super(id);
  }

  public ReturnStatement(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ba05caa2bcaeca1f43f25e676309362a (do not edit this line) */
