/* Generated By:JJTree: Do not edit this line. ReturnStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.ast;

public
class ReturnStatement extends ASTNode {
  public ReturnStatement(int id) {
    super(id);
  }

  public ReturnStatement(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4deb571a4418608ec5ab7a50e3204974 (do not edit this line) */
