/* Generated By:JJTree: Do not edit this line. ScopedCall.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.ast;

public
class ScopedCall extends SimpleNode {
  public ScopedCall(int id) {
    super(id);
  }

  public ScopedCall(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f3533c9608bb127331076ecbb46e3ef8 (do not edit this line) */
