/* Generated By:JJTree: Do not edit this line. ScopedCall.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.ast;

public
class ScopedCall extends ASTNode {
  public ScopedCall(int id) {
    super(id);
  }

  public ScopedCall(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3c1ff3cbd1e1eaf006714fa8d2e7d40d (do not edit this line) */
