/* Generated By:JJTree: Do not edit this line. Statements.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.ast;

public
class Statements extends SimpleNode {
  public Statements(int id) {
    super(id);
  }

  public Statements(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c637b07b539c7283dee68dde695a0da1 (do not edit this line) */
