/* Generated By:JJTree: Do not edit this line. StringConstant.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.ast;

public
class StringConstant extends SimpleNode {
  public StringConstant(int id) {
    super(id);
  }

  public StringConstant(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=360fe9739c587a3cc1fdff9cafcdbb27 (do not edit this line) */
