/* Generated By:JJTree: Do not edit this line. SubroutineBody.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.ast;

public
class SubroutineBody extends ASTNode {
  public SubroutineBody(int id) {
    super(id);
  }

  public SubroutineBody(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9d02a8357f8960be1ea90c73be37b54b (do not edit this line) */
