/* Generated By:JJTree: Do not edit this line. SubroutineBody.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.ast;

public
class SubroutineBody extends SimpleNode {
  public SubroutineBody(int id) {
    super(id);
  }

  public SubroutineBody(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=463115d235bf7c0dbd3a52f3060408a6 (do not edit this line) */
