/* Generated By:JJTree: Do not edit this line. SubroutineDec.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.ast;

public
class SubroutineDec extends SimpleNode {
  public SubroutineDec(int id) {
    super(id);
  }

  public SubroutineDec(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b0fedb7561e9bf828950d1c349561d9e (do not edit this line) */
