/* Generated By:JJTree: Do not edit this line. SubroutineCall.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.ast;

public
class SubroutineCall extends ASTNode {
  public SubroutineCall(int id) {
    super(id);
  }

  public SubroutineCall(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e4bd87ef1cfd8347937078c6ae3dc5bb (do not edit this line) */
