/* Generated By:JJTree: Do not edit this line. Symbol.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.ast;

public
class Symbol extends SimpleNode {
  public Symbol(int id) {
    super(id);
  }

  public Symbol(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=38b9cc5e941089deab7aa472e28c7cfb (do not edit this line) */
