/* Generated By:JJTree: Do not edit this line. Term.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.ast;

public
class Term extends SimpleNode {
  public Term(int id) {
    super(id);
  }

  public Term(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=03f7538c6e91102297d639f65a37b354 (do not edit this line) */
