/* Generated By:JJTree: Do not edit this line. Term.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.ast;

public
class Term extends ASTNode {
  public Term(int id) {
    super(id);
  }

  public Term(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9bbf107f023040e91330a793c87506ac (do not edit this line) */
