/* Generated By:JJTree: Do not edit this line. Type.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.ast;

public
class Type extends ASTNode {
  public Type(int id) {
    super(id);
  }

  public Type(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f2eec9dff6e6b21aa3dee6309d61cd05 (do not edit this line) */
