/* Generated By:JJTree: Do not edit this line. VarDec.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.ast;

public
class VarDec extends SimpleNode {
  public VarDec(int id) {
    super(id);
  }

  public VarDec(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8341b49ebefb4330a94859333cd61000 (do not edit this line) */
