/* Generated By:JJTree: Do not edit this line. VarDec.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.ast;

public
class VarDec extends ASTNode {
  public VarDec(int id) {
    super(id);
  }

  public VarDec(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ebdad0c2f51bfd36a02c75389a345260 (do not edit this line) */
