/* Generated By:JJTree: Do not edit this line. WhileStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.ast;

public
class WhileStatement extends SimpleNode {
  public WhileStatement(int id) {
    super(id);
  }

  public WhileStatement(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=80bf4a55cd867366101985c29b638d11 (do not edit this line) */
