/* Generated By:JJTree: Do not edit this line. ArrayIndexer.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.p11;

public
class ArrayIndexer extends ASTNode {
  public ArrayIndexer(int id) {
    super(id);
  }

  public ArrayIndexer(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e7ba6223e222d8556d1872cb5774f142 (do not edit this line) */
