/* Generated By:JavaCC: Do not edit this line. ASTGentorTreeConstants.java Version 6.0_1 */
package czlab.tecs.p11;

public interface ASTGentorTreeConstants
{
  public int JJTCLASSDEC = 0;
  public int JJTCLASSVARDEC = 1;
  public int JJTKEYWORD = 2;
  public int JJTSYMBOL = 3;
  public int JJTTYPE = 4;
  public int JJTSUBROUTINEDEC = 5;
  public int JJTPARAMETERLIST = 6;
  public int JJTSUBROUTINEBODY = 7;
  public int JJTVARDEC = 8;
  public int JJTSTATEMENTS = 9;
  public int JJTVOID = 10;
  public int JJTLETSTATEMENT = 11;
  public int JJTIFSTATEMENT = 12;
  public int JJTWHILESTATEMENT = 13;
  public int JJTDOSTATEMENT = 14;
  public int JJTRETURNSTATEMENT = 15;
  public int JJTEXPRESSION = 16;
  public int JJTTERM = 17;
  public int JJTSUBROUTINECALL = 18;
  public int JJTEXPRESSIONLIST = 19;
  public int JJTSCOPEDCALL = 20;
  public int JJTINTEGERCONSTANT = 21;
  public int JJTSTRINGCONSTANT = 22;
  public int JJTIDENTIFIER = 23;


  public String[] jjtNodeName = {
    "ClassDec",
    "ClassVarDec",
    "Keyword",
    "Symbol",
    "Type",
    "SubroutineDec",
    "ParameterList",
    "SubroutineBody",
    "VarDec",
    "Statements",
    "void",
    "LetStatement",
    "IfStatement",
    "WhileStatement",
    "DoStatement",
    "ReturnStatement",
    "Expression",
    "Term",
    "SubroutineCall",
    "ExpressionList",
    "ScopedCall",
    "IntegerConstant",
    "StringConstant",
    "Identifier",
  };
}
/* JavaCC - OriginalChecksum=000186a7aebb57ad619afb1f67114cd0 (do not edit this line) */
