/* Generated By:JavaCC: Do not edit this line. ASTGentorTreeConstants.java Version 6.0_1 */
package czlab.tecs.p11;

public interface ASTGentorTreeConstants
{
  public int JJTCLASSDEC = 0;
  public int JJTCLASSVARDEC = 1;
  public int JJTVOID = 2;
  public int JJTSUBROUTINEDEC = 3;
  public int JJTLETSTATEMENT = 4;
  public int JJTIFSTATEMENT = 5;
  public int JJTCONDITION = 6;
  public int JJTIFBLOCK = 7;
  public int JJTELSEBLOCK = 8;
  public int JJTWHILESTATEMENT = 9;
  public int JJTWHILEBLOCK = 10;
  public int JJTDOSTATEMENT = 11;
  public int JJTRETURNSTATEMENT = 12;
  public int JJTEXPRESSION = 13;
  public int JJTTERM = 14;
  public int JJTSUBROUTINECALL = 15;
  public int JJTEXPRESSIONLIST = 16;
  public int JJTOPERATION = 17;
  public int JJTUNARYOPERATION = 18;
  public int JJTINTEGERCONSTANT = 19;
  public int JJTSTRINGCONSTANT = 20;
  public int JJTKEYWORD = 21;


  public String[] jjtNodeName = {
    "ClassDec",
    "ClassVarDec",
    "void",
    "SubroutineDec",
    "LetStatement",
    "IfStatement",
    "Condition",
    "IfBlock",
    "ElseBlock",
    "WhileStatement",
    "WhileBlock",
    "DoStatement",
    "ReturnStatement",
    "Expression",
    "Term",
    "SubroutineCall",
    "ExpressionList",
    "Operation",
    "UnaryOperation",
    "IntegerConstant",
    "StringConstant",
    "Keyword",
  };
}
/* JavaCC - OriginalChecksum=02969366526d624672ffeca892c4bc19 (do not edit this line) */
