/* Generated By:JavaCC: Do not edit this line. ASTGentorTreeConstants.java Version 6.0_1 */
package czlab.tecs.p11;

public interface ASTGentorTreeConstants
{
  public int JJTCLASSDEC = 0;
  public int JJTCLASSVARDEC = 1;
  public int JJTVOID = 2;
  public int JJTSUBROUTINEDEC = 3;
  public int JJTSTATEMENTS = 4;
  public int JJTLETSTATEMENT = 5;
  public int JJTIFSTATEMENT = 6;
  public int JJTIFBLOCK = 7;
  public int JJTELSEBLOCK = 8;
  public int JJTWHILESTATEMENT = 9;
  public int JJTWHILEBLOCK = 10;
  public int JJTDOSTATEMENT = 11;
  public int JJTRETURNSTATEMENT = 12;
  public int JJTEXPRESSION = 13;
  public int JJTTERM = 14;
  public int JJTSUBROUTINECALL = 15;
  public int JJTEXPRESSIONLIST = 16;
  public int JJTOP = 17;


  public String[] jjtNodeName = {
    "ClassDec",
    "ClassVarDec",
    "void",
    "SubroutineDec",
    "Statements",
    "LetStatement",
    "IfStatement",
    "IfBlock",
    "ElseBlock",
    "WhileStatement",
    "WhileBlock",
    "DoStatement",
    "ReturnStatement",
    "Expression",
    "Term",
    "SubroutineCall",
    "ExpressionList",
    "OP",
  };
}
/* JavaCC - OriginalChecksum=1a8fa70114db9ef60471c53606d61c0d (do not edit this line) */
