/* Generated By:JJTree: Do not edit this line. ClassVarDec.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.p11;

public
class ClassVarDec extends ASTNode {
  public ClassVarDec(int id) {
    super(id);
  }

  public ClassVarDec(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4c4d77720523869e1f7f4438a9d1330a (do not edit this line) */
