/* Generated By:JJTree: Do not edit this line. ClassDec.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.p11;

public
class ClassDec extends ASTNode {
  public ClassDec(int id) {
    super(id);
  }

  public ClassDec(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=59d0b0edb187f469220e6739e2c7d233 (do not edit this line) */
