/* Generated By:JJTree: Do not edit this line. Condition.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.p11;

public
class Condition extends ASTNode {
  public Condition(int id) {
    super(id);
  }

  public Condition(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=91d33496fe921487b0865432081c2e6c (do not edit this line) */
