/* Generated By:JJTree: Do not edit this line. DoStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.p11;

public
class DoStatement extends ASTNode {
  public DoStatement(int id) {
    super(id);
  }

  public DoStatement(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=21cba4b6347bc075bc33e75fc85ec4a3 (do not edit this line) */
