/* Generated By:JJTree: Do not edit this line. ElseBlock.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.p11;

public
class ElseBlock extends ASTNode {
  public ElseBlock(int id) {
    super(id);
  }

  public ElseBlock(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5cc282cc0416a28a576575c2788e910f (do not edit this line) */
