/* Generated By:JJTree: Do not edit this line. ExpressionList.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.p11;

public
class ExpressionList extends ASTNode {
  public ExpressionList(int id) {
    super(id);
  }

  public ExpressionList(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=158e79d8a47b17ad3838e928b958551c (do not edit this line) */
