/* Generated By:JJTree: Do not edit this line. Identifier.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.p11;

public
class Identifier extends ASTNode {
  public Identifier(int id) {
    super(id);
  }

  public Identifier(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=06618b5d2fceb87fd26fb5805b487252 (do not edit this line) */
