/* Generated By:JJTree: Do not edit this line. IfBlock.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.p11;

public
class IfBlock extends ASTNode {
  public IfBlock(int id) {
    super(id);
  }

  public IfBlock(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=eeb6907e0d0f2689f9d2d8a6dc61f660 (do not edit this line) */
