/* Generated By:JJTree: Do not edit this line. IfStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.p11;

public
class IfStatement extends ASTNode {
  public IfStatement(int id) {
    super(id);
  }

  public IfStatement(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b4c45236862c53e9df59fd40aab1ff35 (do not edit this line) */
