/* Generated By:JJTree: Do not edit this line. IntegerConstant.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.p11;

public
class IntegerConstant extends ASTNode {
  public IntegerConstant(int id) {
    super(id);
  }

  public IntegerConstant(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1c990dc80a7eaecddf90de884a80bb3e (do not edit this line) */
