/* Generated By:JJTree: Do not edit this line. Keyword.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.p11;

public
class Keyword extends ASTNode {
  public Keyword(int id) {
    super(id);
  }

  public Keyword(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a9523b9d189ad317894b1ad424f1ee78 (do not edit this line) */
