/* Generated By:JJTree: Do not edit this line. LeftBrac.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.p11;

public
class LeftBrac extends ASTNode {
  public LeftBrac(int id) {
    super(id);
  }

  public LeftBrac(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d46d598c2044b1b4986804e0fbc630d2 (do not edit this line) */
