/* Generated By:JJTree: Do not edit this line. OP.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.p11;

public
class OP extends ASTNode {
  public OP(int id) {
    super(id);
  }

  public OP(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5a913208471d662dd87a947fcfe184e6 (do not edit this line) */
