/* Generated By:JJTree: Do not edit this line. Operation.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.p11;

public
class Operation extends ASTNode {
  public Operation(int id) {
    super(id);
  }

  public Operation(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8717430954f05f57fa9a509b30a47323 (do not edit this line) */
