/* Generated By:JJTree: Do not edit this line. ParameterList.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.p11;

public
class ParameterList extends ASTNode {
  public ParameterList(int id) {
    super(id);
  }

  public ParameterList(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=778de2de0467ff90b0aa33a45a6220ef (do not edit this line) */
