/* Generated By:JJTree: Do not edit this line. RightBrac.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.p11;

public
class RightBrac extends ASTNode {
  public RightBrac(int id) {
    super(id);
  }

  public RightBrac(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b994734994d4f1c72ec63a3e2cb4d7b9 (do not edit this line) */
