/* Generated By:JJTree: Do not edit this line. ScopedCall.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.p11;

public
class ScopedCall extends ASTNode {
  public ScopedCall(int id) {
    super(id);
  }

  public ScopedCall(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ea8c6f8214478015d5f6b80fa38ae36f (do not edit this line) */
