/* Generated By:JJTree: Do not edit this line. Statements.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.p11;

public
class Statements extends ASTNode {
  public Statements(int id) {
    super(id);
  }

  public Statements(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3b2693e6f3102e8bfdffbd8e77cf6f8f (do not edit this line) */
