/* Generated By:JJTree: Do not edit this line. StringConstant.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.p11;

public
class StringConstant extends ASTNode {
  public StringConstant(int id) {
    super(id);
  }

  public StringConstant(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=847a74e92026d2d364bd3c6f41572737 (do not edit this line) */
