/* Generated By:JJTree: Do not edit this line. SubroutineBody.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.p11;

public
class SubroutineBody extends ASTNode {
  public SubroutineBody(int id) {
    super(id);
  }

  public SubroutineBody(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c266f6a83af0c47d2b1dc3690b6765d5 (do not edit this line) */
