/* Generated By:JJTree: Do not edit this line. SubroutineCall.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.p11;

public
class SubroutineCall extends ASTNode {
  public SubroutineCall(int id) {
    super(id);
  }

  public SubroutineCall(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e6abd5ff4a43c8dff4573751077294bf (do not edit this line) */
