/* Generated By:JJTree: Do not edit this line. Symbol.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.p11;

public
class Symbol extends ASTNode {
  public Symbol(int id) {
    super(id);
  }

  public Symbol(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8c1e139d032466856fed3815233a7104 (do not edit this line) */
