/* Generated By:JJTree: Do not edit this line. Type.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.p11;

public
class Type extends ASTNode {
  public Type(int id) {
    super(id);
  }

  public Type(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=aeef3ab06394c8fe44b558e3590fd554 (do not edit this line) */
