/* Generated By:JJTree: Do not edit this line. UnaryOperation.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.p11;

public
class UnaryOperation extends ASTNode {
  public UnaryOperation(int id) {
    super(id);
  }

  public UnaryOperation(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6ff4c026f43eb11cf6930f57be98620a (do not edit this line) */
