/* Generated By:JJTree: Do not edit this line. VarDec.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.p11;

public
class VarDec extends ASTNode {
  public VarDec(int id) {
    super(id);
  }

  public VarDec(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=09bed116e37da2a204326a6f4562df8a (do not edit this line) */
