/* Generated By:JJTree: Do not edit this line. WhileStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.p11;

public
class WhileStatement extends ASTNode {
  public WhileStatement(int id) {
    super(id);
  }

  public WhileStatement(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c91e3d2c86e3368921d25f29d45a1d99 (do not edit this line) */
