/* Generated By:JJTree: Do not edit this line. WhileBlock.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package czlab.tecs.p11;

public
class WhileBlock extends ASTNode {
  public WhileBlock(int id) {
    super(id);
  }

  public WhileBlock(ASTGentor p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=153bc2327dd70d7b0d6a702ef15c5011 (do not edit this line) */
